# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
        ('property_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bonus_spaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='normal_amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='safety_amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bedtype',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bonus_spaces',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='com_space',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='normal_amenities',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='safety_amenities',
        ),
        migrations.AddField(
            model_name='listing',
            name='bedsize',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='common_space',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='host_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='host_listing', to='users_app.User'),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default='Castle', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(default='Home', max_length=15),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(default='Apartment', max_length=15),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='room_type',
            field=models.CharField(default='Private room', max_length=15),
        ),
        migrations.AddField(
            model_name='safety_amenities',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_amenity', to='property_details.listing'),
        ),
        migrations.AddField(
            model_name='review',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to='property_details.listing'),
        ),
        migrations.AddField(
            model_name='review',
            name='rated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='users_app.User'),
        ),
        migrations.AddField(
            model_name='normal_amenities',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normal_amenity', to='property_details.listing'),
        ),
        migrations.AddField(
            model_name='bonus_spaces',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_space', to='property_details.listing'),
        ),
    ]
