# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonus_spaces',
            old_name='location',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='normal_amenities',
            old_name='location',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='safety_amenities',
            old_name='location',
            new_name='listing',
        ),
    ]
