# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonus_spaces',
            old_name='location',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='normal_amenities',
            old_name='location',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='safety_amenities',
            old_name='location',
            new_name='listing',
        ),
        migrations.AlterField(
            model_name='listing',
            name='host_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='host_listing', to='users_app.User'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(default='Castle', max_length=20),
        ),
    ]
