# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_details', '0002_auto_20171026_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m'),
        ),
    ]
