import bcrypt
from ..users_app.models import User
from ..property_details.models import listing
from random import randint

def create_dummy_users():
    User.objects.create(	first_name='lexie',	last_name='pollard',	birthday='1975-11-01',	email='Lexie.POLLA6461@yahoo.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(303) 661-7009',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='warren',	user_description='this is a description'	)
    User.objects.create(	first_name='emery',	last_name='campos',	birthday='1976-11-01',	email='Emery.CAMPO8866@live.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(301) 131-9283',	gender='M',	preferred_language='EN',	preferred_currency='USD',	location='montgomery',	user_description='this is a description'	)
    User.objects.create(	first_name='kara',	last_name='giles',	birthday='1977-11-01',	email='Kara.GILE9910@yahoo.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(409) 409-7658',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='henderson',	user_description='this is a description'	)
    User.objects.create(	first_name='porter',	last_name='atkinson',	birthday='1978-11-01',	email='Por.ATKINS5033@hushmail.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(562) 306-2239',	gender='M',	preferred_language='EN',	preferred_currency='USD',	location='cary',	user_description='this is a description'	)
    User.objects.create(	first_name='harry',	last_name='kelly',	birthday='1979-11-01',	email='Har.KEL7426@live.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(425) 260-7670',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='stamford',	user_description='this is a description'	)
    User.objects.create(	first_name='aryana',	last_name='roman',	birthday='1980-11-01',	email='Arya.RO2266@live.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(253) 789-0516',	gender='M',	preferred_language='EN',	preferred_currency='USD',	location='denver',	user_description='this is a description'	)
    User.objects.create(	first_name='madilyn',	last_name='carlson',	birthday='1981-11-01',	email='Madil.CARLS5371@yahoo.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(510) 373-3967',	gender='M',	preferred_language='EN',	preferred_currency='USD',	location='fayetteville',	user_description='this is a description'	)
    User.objects.create(	first_name='lena',	last_name='webster',	birthday='1982-11-01',	email='Len.WEBSTE8879@yahoo.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(417) 697-7103',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='hartford',	user_description='this is a description'	)
    User.objects.create(	first_name='douglas',	last_name='matthews',	birthday='1983-11-01',	email='Dou.MATT6153@hushmail.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(662) 195-4067',	gender='M',	preferred_language='EN',	preferred_currency='USD',	location='omaha',	user_description='this is a description'	)
    User.objects.create(	first_name='saul',	last_name='barrett',	birthday='1984-11-01',	email='Saul.BARRET6581@gmail.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(513) 558-7536',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='overland park',	user_description='this is a description'	)
    User.objects.create(	first_name='kiana',	last_name='rollins',	birthday='1985-11-01',	email='Ki.ROLLINS9997@live.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(512) 751-1268',	gender='M',	preferred_language='EN',	preferred_currency='USD',	location='mesa',	user_description='this is a description'	)
    User.objects.create(	first_name='caitlyn',	last_name='burt',	birthday='1986-11-01',	email='Caitlyn.BURT2020@mail2web.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(361) 513-0210',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='fort collins',	user_description='this is a description'	)
    User.objects.create(	first_name='arjun',	last_name='love',	birthday='1987-11-01',	email='Arj.LOVE5807@live.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(337) 544-5159',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='louisville',	user_description='this is a description'	)
    User.objects.create(	first_name='micheal',	last_name='diaz',	birthday='1988-11-01',	email='Michea.DIA8089@live.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(276) 435-3099',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='cary',	user_description='this is a description'	)
    User.objects.create(	first_name='vanessa',	last_name='carver',	birthday='1989-11-01',	email='Van.CARV4601@mail2web.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(816) 474-7040',	gender='M',	preferred_language='EN',	preferred_currency='USD',	location='fremont',	user_description='this is a description'	)
    User.objects.create(	first_name='micah',	last_name='ferguson',	birthday='1990-11-01',	email='Mic.FERGUS5634@mail2web.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(985) 796-6733',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='hampton',	user_description='this is a description'	)
    User.objects.create(	first_name='kaelynn',	last_name='wood',	birthday='1991-11-01',	email='Kae.WOOD5621@yahoo.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(907) 597-3131',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='columbus',	user_description='this is a description'	)
    User.objects.create(	first_name='callen',	last_name='ramsey',	birthday='1992-11-01',	email='Call.RAMSEY7612@live.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(510) 141-9541',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='lansing',	user_description='this is a description'	)
    User.objects.create(	first_name='kayla',	last_name='sykes',	birthday='1993-11-01',	email='Kayla.SYKE6425@hushmail.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(475) 269-7009',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='tucson',	user_description='this is a description'	)
    User.objects.create(	first_name='jolene',	last_name='oconnor',	birthday='1994-11-01',	email='Jol.OCONNO4971@hushmail.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(623) 490-1310',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='orlando',	user_description='this is a description'	)
    User.objects.create(	first_name='hana',	last_name='reese',	birthday='1995-11-01',	email='Ha.RE4770@live.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(314) 710-6480',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='washington',	user_description='this is a description'	)
    User.objects.create(	first_name='adriel',	last_name='davidson',	birthday='1996-11-01',	email='Adrie.DAVIDSO7547@yahoo.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(503) 547-1502',	gender='M',	preferred_language='EN',	preferred_currency='USD',	location='corpus christi',	user_description='this is a description'	)
    User.objects.create(	first_name='laylah',	last_name='mcfarland',	birthday='1997-11-01',	email='Layl.MCFARL2569@hushmail.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(520) 831-0773',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='allentown',	user_description='this is a description'	)
    User.objects.create(	first_name='jaidyn',	last_name='lopez',	birthday='1998-11-01',	email='Jaid.LOP5399@gmail.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(281) 955-1960',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='fort wayne',	user_description='this is a description'	)
    User.objects.create(	first_name='rohan',	last_name='oconnor',	birthday='1999-11-01',	email='Rohan.OCON3339@live.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(702) 168-5673',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='clarksville',	user_description='this is a description'	)
    User.objects.create(	first_name='sierra',	last_name='parrish',	birthday='2000-11-01',	email='Sie.PARRISH2923@yahoo.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(601) 403-9587',	gender='M',	preferred_language='EN',	preferred_currency='USD',	location='indianapolis',	user_description='this is a description'	)
    User.objects.create(	first_name='urijah',	last_name='phillips',	birthday='2001-11-01',	email='Uri.PHILLIPS8362@live.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(502) 353-7646',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='dayton',	user_description='this is a description'	)
    User.objects.create(	first_name='zane',	last_name='sandoval',	birthday='2002-11-01',	email='Zane.SANDOVAL9235@yahoo.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(218) 382-1647',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='lansing',	user_description='this is a description'	)
    User.objects.create(	first_name='kallie',	last_name='wells',	birthday='2003-11-01',	email='Kalli.WE3709@gmail.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(831) 787-4750',	gender='M',	preferred_language='EN',	preferred_currency='USD',	location='orlando',	user_description='this is a description'	)
    User.objects.create(	first_name='hadley',	last_name='calhoun',	birthday='2004-11-01',	email='Hadley.CALHO1406@gmail.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(205) 612-3261',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='peoria',	user_description='this is a description'	)
    User.objects.create(	first_name='blaine',	last_name='brewer',	birthday='2005-11-01',	email='Blaine.BRE9353@live.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(740) 199-9618',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='los angeles',	user_description='this is a description'	)
    User.objects.create(	first_name='miranda',	last_name='simon',	birthday='2006-11-01',	email='Miranda.SIMO2687@mail2web.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(404) 280-9066',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='worcester',	user_description='this is a description'	)
    User.objects.create(	first_name='sarahi',	last_name='hammond',	birthday='2007-11-01',	email='Sarahi.HAMMON9434@live.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(252) 219-6391',	gender='M',	preferred_language='EN',	preferred_currency='USD',	location='des moines',	user_description='this is a description'	)
    User.objects.create(	first_name='arielle',	last_name='wilder',	birthday='2008-11-01',	email='Ari.WIL7275@mail2web.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(609) 765-2555',	gender='M',	preferred_language='EN',	preferred_currency='USD',	location='albuquerque',	user_description='this is a description'	)
    User.objects.create(	first_name='lilliana',	last_name='riley',	birthday='2009-11-01',	email='Lill.RIL2605@hushmail.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(636) 681-6932',	gender='M',	preferred_language='EN',	preferred_currency='USD',	location='garland',	user_description='this is a description'	)
    User.objects.create(	first_name='owen',	last_name='lopez',	birthday='2010-11-01',	email='Ow.LOP6781@yahoo.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(614) 198-9616',	gender='M',	preferred_language='EN',	preferred_currency='USD',	location='st. louis',	user_description='this is a description'	)
    User.objects.create(	first_name='kamren',	last_name='ayala',	birthday='2011-11-01',	email='Kamren.AYA1522@yahoo.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(936) 276-3828',	gender='M',	preferred_language='EN',	preferred_currency='USD',	location='cincinnati',	user_description='this is a description'	)
    User.objects.create(	first_name='cayson',	last_name='mullins',	birthday='2012-11-01',	email='Cayso.MULLIN2672@hushmail.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(772) 616-9481',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='amarillo',	user_description='this is a description'	)
    User.objects.create(	first_name='gianni',	last_name='whitfield',	birthday='2013-11-01',	email='Gianni.WHITF8488@mail2web.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(775) 443-5075',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='columbia',	user_description='this is a description'	)
    User.objects.create(	first_name='matthew',	last_name='murphy',	birthday='2014-11-01',	email='Matthew.MUR7749@hushmail.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(402) 125-0215',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='columbus',	user_description='this is a description'	)
    User.objects.create(	first_name='charli',	last_name='ramirez',	birthday='2015-11-01',	email='Charli.RAMI3464@yahoo.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(303) 977-9732',	gender='M',	preferred_language='EN',	preferred_currency='USD',	location='rockford',	user_description='this is a description'	)
    User.objects.create(	first_name='amy',	last_name='cortez',	birthday='2016-11-01',	email='Am.CORT9944@gmail.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(469) 168-9200',	gender='M',	preferred_language='EN',	preferred_currency='USD',	location='akron',	user_description='this is a description'	)
    User.objects.create(	first_name='avianna',	last_name='mccoy',	birthday='2017-11-01',	email='Avianna.MCCO3424@live.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(214) 436-9889',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='st. paul',	user_description='this is a description'	)
    User.objects.create(	first_name='kenneth',	last_name='stephenson',	birthday='2018-11-01',	email='Kenn.STEPHENSO8570@mail2web.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(401) 891-0481',	gender='M',	preferred_language='EN',	preferred_currency='USD',	location='little rock',	user_description='this is a description'	)
    User.objects.create(	first_name='evelyn',	last_name='hernandez',	birthday='2019-11-01',	email='Evely.HERNANDE5667@yahoo.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(720) 260-0285',	gender='M',	preferred_language='EN',	preferred_currency='USD',	location='garland',	user_description='this is a description'	)
    User.objects.create(	first_name='orlando',	last_name='knox',	birthday='2020-11-01',	email='Orland.KNOX7166@yahoo.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(412) 993-5000',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='fort worth',	user_description='this is a description'	)
    User.objects.create(	first_name='joseph',	last_name='carver',	birthday='2021-11-01',	email='Jose.CAR2605@live.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(712) 144-6585',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='lubbock',	user_description='this is a description'	)
    User.objects.create(	first_name='alicia',	last_name='daniel',	birthday='2022-11-01',	email='Alici.DANIEL2202@yahoo.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(623) 683-8786',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='wichita',	user_description='this is a description'	)
    User.objects.create(	first_name='jaden',	last_name='oneill',	birthday='2023-11-01',	email='Ja.ONEIL8231@hushmail.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(502) 566-2424',	gender='M',	preferred_language='EN',	preferred_currency='USD',	location='knoxville',	user_description='this is a description'	)
    User.objects.create(	first_name='tori',	last_name='ortega',	birthday='2024-11-01',	email='Tor.ORTE8728@live.com',	password =bcrypt.hashpw('password'.encode(), bcrypt.gensalt()),	phone_number='(727) 317-4419',	gender='F',	preferred_language='EN',	preferred_currency='USD',	location='augusta',	user_description='this is a description'	)
    return

def create_dummy_listings():
    x = pick_picture()
    listing.objects.create(	title='Natoque donec aliquet ut sociosqu.',	listing_type='Home', property_type='Condominium', room_type='Shared Room', ded_space='True',guests='13',beds='9',bedsize='King',
        common_space='Floor Matress',bathrooms='9',	Country='United States',street_one='2963 brighton',	street_two='',city='jersey city',state='new jersey',zip_code='7131', 
        rate='153', photo1='uploads/2017/10/house'+str(x)+'.1.jpg', photo2='uploads/2017/10/house'+str(x)+'.2.jpg',  description='Lorem ipsum tincidunt euismod donec taciti volutpat inceptos hendrerit lacinia.Tristique tristique vestibulum luctus in gravida class hac integer felis.Interdum sociis donec leo donec augue sapien inceptos.Eget parturient mauris accumsan, ante ornare consequat fusce mollis fermentum.Est litora posuere nisi penatibus non ultrices habitant luctus.Sem viverra felis diam sit nam magnis dolor sociosqu venenatis lacus lorem.Conubia nascetur primis litora euismod nibh per ac egestas pulvinar lectus?Sapien, fermentum cras libero magnis litora nibh ultricies egestas pretium tortor mollis.Sit sit vel, vulputate eleifend turpis at suscipit facilisis metus.Sed dictum per; habitant in fringilla a elementum!'	)
    x = pick_picture()
    listing.objects.create(	title='Natoque donec aliquet ut sociosqu.',	listing_type='Home',	property_type='Condominium',	room_type='Shared Room',	ded_space='True',	guests='13',	beds='9',	bedsize='King',	common_space='Floor Matress',	bathrooms='9',	Country='United States',	street_one='2963 brighton',	street_two='',	city='jersey city',	state='new jersey',	zip_code='7131',	rate='153',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum tincidunt euismod donec taciti volutpat inceptos hendrerit lacinia.Tristique tristique vestibulum luctus in gravida class hac integer felis.Interdum sociis donec leo donec augue sapien inceptos.Eget parturient mauris accumsan, ante ornare consequat fusce mollis fermentum.Est litora posuere nisi penatibus non ultrices habitant luctus.Sem viverra felis diam sit nam magnis dolor sociosqu venenatis lacus lorem.Conubia nascetur primis litora euismod nibh per ac egestas pulvinar lectus?Sapien, fermentum cras libero magnis litora nibh ultricies egestas pretium tortor mollis.Sit sit vel, vulputate eleifend turpis at suscipit facilisis metus.Sed dictum per; habitant in fringilla a elementum!',	)
    x = pick_picture()
    listing.objects.create(	title='Amet commodo porttitor conubia odio!',	listing_type='Hotel',	property_type='Apartment',	room_type='Shared Room',	ded_space='False',	guests='8',	beds='2',	bedsize='Sofa bed',	common_space='Sofa Bed',	bathrooms='10',	Country='United States',	street_one='499 fairbanks',	street_two='',	city='columbia',	state='south carolina',	zip_code='29079',	rate='201',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum id mattis integer tincidunt mi pulvinar euismod congue curae; imperdiet vestibulum risus!Nibh condimentum semper consequat sociosqu rutrum, egestas leo vivamus cubilia potenti.Magnis accumsan nisi sollicitudin ornare etiam gravida etiam platea.Sollicitudin suspendisse fames sit ridiculus morbi habitasse commodo dui.Non leo velit imperdiet rutrum himenaeos cursus vivamus urna elit morbi mi.Neque curae; morbi quisque a ante quam volutpat turpis.Dapibus placerat vehicula massa vulputate ullamcorper senectus montes bibendum aliquet.Donec pretium cubilia porta curabitur turpis egestas justo dictum luctus curae;.Suscipit metus vitae urna gravida suscipit nascetur mauris?Vitae velit litora facilisis sociosqu non curae; et amet.',	)
    x = pick_picture()
    listing.objects.create(	title='Urna velit sagittis congue blandit?',	listing_type='Something else',	property_type='TownHouse',	room_type='Entire Place',	ded_space='False',	guests='7',	beds='6',	bedsize='King',	common_space='Sofa Bed',	bathrooms='3',	Country='United States',	street_one='6314 lunt',	street_two='',	city='lincoln',	state='nebraska',	zip_code='68041 ',	rate='124',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum ut ridiculus mi et orci lectus lorem sodales eleifend at?Accumsan quam inceptos lobortis sociis euismod neque nunc cras!Nisl placerat hendrerit metus a tortor elit odio cras aliquet faucibus.Nostra, consectetur risus metus imperdiet penatibus purus gravida mi lacus cras condimentum.Porta varius hac enim per sagittis cum, cubilia placerat luctus!Posuere ante vestibulum venenatis etiam parturient consectetur lorem.Pulvinar accumsan primis sollicitudin netus fermentum egestas facilisis magnis tempus facilisis urna!Hac nam aliquam curae; pulvinar at velit posuere proin.Hendrerit blandit imperdiet ligula libero aliquet cubilia elementum natoque maecenas blandit.Integer penatibus nunc nam neque nunc hendrerit dictumst taciti suscipit.',	)
    x = pick_picture()
    listing.objects.create(	title='Sodales rutrum, cursus lorem curabitur.',	listing_type='Home',	property_type='Condominium',	room_type='Shared Room',	ded_space='True',	guests='1',	beds='3',	bedsize='Sofa bed',	common_space='Sofa Bed',	bathrooms='11',	Country='United States',	street_one='5911 50th',	street_two='',	city='springfield',	state='missouri',	zip_code='65793',	rate='218',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum gravida senectus curae; iaculis mus quis imperdiet elit curabitur justo commodo!Parturient fermentum mi iaculis quisque sollicitudin torquent ipsum faucibus hac sodales.Nunc semper natoque maecenas eros nostra diam sagittis ultrices nisi tempor.Facilisis erat vestibulum laoreet molestie libero eu proin.Metus rutrum viverra posuere vehicula venenatis, iaculis augue!Taciti vehicula facilisis tellus risus vulputate magnis risus sem elit orci felis.Maecenas et condimentum hendrerit in dictumst faucibus convallis mus nisi?Tristique pellentesque sagittis blandit quis leo vehicula tristique luctus?Dolor conubia ligula magna enim ad eleifend nisl hendrerit suspendisse.Aliquet, vehicula eget imperdiet nam risus tellus adipiscing?',	)
    x = pick_picture()
    listing.objects.create(	title='Faucibus nostra suscipit id cursus.',	listing_type='Hotel',	property_type='Apartment',	room_type='Shared Room',	ded_space='True',	guests='9',	beds='5',	bedsize='Queen',	common_space='Floor Matress',	bathrooms='10',	Country='United States',	street_one='2028 kasson',	street_two='',	city='laredo',	state='texas',	zip_code='78047',	rate='166',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum netus blandit metus morbi auctor parturient suspendisse ligula, tempus natoque dictumst.Laoreet ultrices himenaeos erat parturient etiam magna porttitor ultricies senectus lorem laoreet.Rhoncus justo feugiat eu convallis elit porttitor non urna fusce malesuada.Quisque quisque lorem eu scelerisque vulputate dictum eros fringilla eros vehicula!Tellus himenaeos metus dolor ultricies euismod orci taciti himenaeos congue.Primis quis class mauris parturient bibendum venenatis consectetur.Aliquam auctor massa mauris suspendisse vehicula hac facilisis montes.Imperdiet dui aliquam convallis habitant habitant velit nostra senectus facilisis fusce consequat!Turpis lorem platea a augue porta nec porttitor?Nisi elit nulla nibh molestie curae; fermentum facilisi enim.',	)
    x = pick_picture()
    listing.objects.create(	title='Nibh netus elementum pulvinar magnis.',	listing_type='Hotel',	property_type='Guesthouse',	room_type='Shared Room',	ded_space='True',	guests='9',	beds='6',	bedsize='King',	common_space='Sofa Bed',	bathrooms='10',	Country='United States',	street_one='9395 east end',	street_two='',	city='stamford',	state='connecticut',	zip_code='6961',	rate='54',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum felis semper habitant dictum sapien magna taciti est pellentesque tortor hac mattis?Consequat euismod quam posuere elementum inceptos neque senectus suscipit habitasse aptent.Cubilia pellentesque faucibus nec donec himenaeos justo eleifend parturient tempus justo molestie.Quis curabitur non mus volutpat condimentum tristique ultricies habitant placerat risus habitasse.At amet, integer vestibulum vehicula ultricies ultricies rhoncus habitasse.Enim ornare ultrices taciti suscipit ipsum integer sit.Commodo curabitur diam libero leo odio convallis vulputate magnis euismod hendrerit euismod.Cubilia tempus dictumst accumsan nulla sapien interdum volutpat!Quam nisl sapien purus elit cubilia feugiat, consectetur duis.Fames dictum nam consectetur senectus commodo suspendisse eget eros aptent primis elementum?',	)
    x = pick_picture()
    listing.objects.create(	title='Diam ultrices integer posuere varius.',	listing_type='Something else',	property_type='Condominium',	room_type='Private Room',	ded_space='True',	guests='15',	beds='8',	bedsize='Sofa bed',	common_space='Couch',	bathrooms='6',	Country='United States',	street_one='1972 kearsarge',	street_two='',	city='augusta',	state='georgia',	zip_code='30974',	rate='300',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum blandit lobortis himenaeos nullam primis fusce sem sociis rutrum.Non orci nunc cursus vel mauris pulvinar integer quisque netus felis velit.Class accumsan nostra sagittis diam dictum semper felis tristique egestas platea.Nostra nam convallis, iaculis nisi laoreet fames scelerisque lorem.Augue nostra dictum sapien nulla tortor urna aenean habitasse.Lorem nisi lorem tortor placerat nunc malesuada mollis dictum laoreet class fermentum.Cursus et vitae posuere semper ipsum etiam dictumst magna.Dignissim dapibus nam nunc hendrerit praesent quisque vehicula id est ullamcorper mus.Donec id metus sapien bibendum suspendisse viverra vehicula primis.Sagittis dis fusce sem in parturient ut maecenas faucibus montes vitae ultricies.',	)
    x = pick_picture()
    listing.objects.create(	title='Ornare accumsan augue senectus faucibus.',	listing_type='Home',	property_type='Condominium',	room_type='Private Room',	ded_space='False',	guests='4',	beds='9',	bedsize='Double',	common_space='Sofa Bed',	bathrooms='6',	Country='United States',	street_one='6545 sayre',	street_two='',	city='columbus',	state='georgia',	zip_code='31917',	rate='142',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum ipsum nibh curae; nascetur velit aptent est iaculis!Magna massa in rutrum maecenas quisque bibendum nam interdum porttitor.Volutpat ligula arcu proin posuere gravida suspendisse magnis elit cursus cras mattis.Condimentum imperdiet dignissim sociosqu lacus fusce quisque a rutrum luctus leo donec.Dui phasellus habitasse neque sodales mattis ornare augue quisque elementum justo.Aptent elit elit sodales dolor duis tellus eros cubilia sodales.Natoque himenaeos eros diam metus rutrum facilisi inceptos.Ligula sem lobortis laoreet dui sapien blandit diam facilisis vehicula penatibus blandit!Sapien maecenas laoreet cras hendrerit fames auctor penatibus quam etiam auctor parturient.Malesuada porta nunc eros ornare dui quis conubia sagittis lorem adipiscing.',	)
    x = pick_picture()
    listing.objects.create(	title='Urna ullamcorper curae; diam quam.',	listing_type='Home',	property_type='House',	room_type='Private Room',	ded_space='False',	guests='15',	beds='12',	bedsize='Queen',	common_space='Sofa Bed',	bathrooms='8',	Country='United States',	street_one='7808 lake shore lower',	street_two='',	city='hampton',	state='virginia',	zip_code='23628',	rate='146',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum vulputate fermentum montes montes id facilisi proin dapibus diam venenatis commodo.Blandit quam facilisis auctor dignissim fermentum praesent sodales egestas.Fames, nisi lacinia non vel massa lectus cursus.Penatibus praesent per molestie suspendisse natoque ad nisl tortor convallis felis fames.Purus dignissim euismod tincidunt nunc sollicitudin duis justo fames lobortis neque eros!Tempor placerat viverra mattis amet sodales bibendum nulla tempus.Fermentum, sagittis id et quis eu scelerisque habitasse quisque vivamus dui.Praesent eget ligula suscipit aptent cursus tortor odio primis.Mollis consectetur sagittis ac auctor amet malesuada nascetur, ultricies ad integer tortor.Facilisis orci lacinia non egestas taciti litora pellentesque pretium!',	)
    x = pick_picture()
    listing.objects.create(	title='Aenean ipsum pharetra, interdum ipsum.',	listing_type='Home',	property_type='Guesthouse',	room_type='Shared Room',	ded_space='True',	guests='6',	beds='1',	bedsize='King',	common_space='Couch',	bathrooms='16',	Country='United States',	street_one='4063 23rd',	street_two='',	city='columbus',	state='georgia',	zip_code='31914',	rate='298',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum tortor vivamus tortor nulla integer semper eleifend habitant eros imperdiet.Felis sed accumsan sapien risus lorem lobortis parturient dui!Elit dignissim torquent integer praesent facilisi praesent nisl faucibus aliquam risus placerat.Velit ornare vel eros vulputate amet senectus faucibus dictum.Porta torquent eleifend enim enim luctus varius lacinia placerat.Sollicitudin quisque class quisque venenatis ultricies lacus, nunc rhoncus.Nostra gravida risus vestibulum erat fusce volutpat nulla pretium!Faucibus dictumst tellus adipiscing vehicula in erat metus blandit consectetur congue.Placerat risus nibh vestibulum sociosqu volutpat cursus imperdiet eget taciti!Ultricies dapibus ligula penatibus nisi interdum nisi id aliquet semper.',	)
    x = pick_picture()
    listing.objects.create(	title='Curae; cum dapibus orci, ipsum.',	listing_type='Hotel',	property_type='Guest suite',	room_type='Shared Room',	ded_space='False',	guests='16',	beds='8',	bedsize='Double',	common_space='Couch',	bathrooms='8',	Country='United States',	street_one='8661 arbour',	street_two='',	city='topeka',	state='kansas',	zip_code='66616',	rate='258',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum purus pellentesque cras laoreet proin dui magna ridiculus montes.Lobortis luctus condimentum, hendrerit torquent malesuada arcu maecenas!Nec nulla elementum luctus metus per inceptos pharetra magnis ante fringilla.Curabitur consequat laoreet dignissim quisque et mattis eget et malesuada sodales!Facilisis primis habitasse auctor hendrerit nam ad dignissim dapibus etiam cum nibh.Ad quisque eros penatibus potenti, lacus orci torquent.Conubia ullamcorper natoque himenaeos laoreet eleifend parturient fermentum dolor libero vel?Sociis tortor consequat duis a justo integer morbi.Semper donec mattis cursus sagittis justo ac curae; vitae; hendrerit suspendisse vitae.Sodales pretium suspendisse habitasse eget turpis laoreet urna a.',	)
    x = pick_picture()
    listing.objects.create(	title='Lorem a proin penatibus mollis.',	listing_type='Something else',	property_type='TownHouse',	room_type='Shared Room',	ded_space='False',	guests='6',	beds='15',	bedsize='Double',	common_space='Floor Matress',	bathrooms='16',	Country='United States',	street_one='4085 oakley',	street_two='',	city='springfield',	state='missouri',	zip_code='65762',	rate='106',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum ullamcorper metus aliquam tortor lobortis quis nunc vivamus sagittis.Potenti tristique auctor tellus senectus cum montes malesuada.Phasellus pulvinar accumsan fringilla fames sodales turpis conubia id potenti.Purus proin ad sapien sociosqu ipsum nostra iaculis habitant sodales fames bibendum!Fusce curabitur felis praesent facilisis class habitant nunc.Ut dolor gravida ullamcorper mollis tortor torquent erat integer nascetur.Est eu potenti netus gravida consectetur ornare adipiscing adipiscing.Dictumst pellentesque sit sollicitudin fusce tortor porta dignissim dapibus porta erat etiam.Ad potenti fames sollicitudin augue risus tristique consectetur natoque praesent.Iaculis, cras nullam congue nec montes libero luctus hendrerit accumsan dictumst posuere.',	)
    x = pick_picture()
    listing.objects.create(	title='Curabitur per arcu tincidunt conubia.',	listing_type='Home',	property_type='Guesthouse',	room_type='Shared Room',	ded_space='True',	guests='9',	beds='1',	bedsize='Queen',	common_space='Sofa Bed',	bathrooms='2',	Country='United States',	street_one='6118 kedvale',	street_two='',	city='boston',	state='massachusetts',	zip_code='2572',	rate='56',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum accumsan metus torquent leo interdum massa lacinia praesent cum auctor.Felis parturient per viverra, interdum aptent posuere vitae.Curabitur elementum imperdiet ante suspendisse bibendum aenean sit per.Sem ipsum semper at ut quis fames vestibulum sociosqu eros.Ad enim, quis nisl nec suspendisse fames bibendum proin quis quam.Cum per habitasse blandit adipiscing etiam elit fermentum tortor elit rhoncus.Nostra pretium a eu turpis, curabitur venenatis curae; senectus ut.Cum aliquam mi sem cras ad tempus cursus.Nibh in erat hendrerit cubilia massa sociosqu at iaculis.Aliquam litora eget iaculis nulla blandit ligula tristique lectus lobortis.',	)
    x = pick_picture()
    listing.objects.create(	title='Sollicitudin nascetur curabitur tempor montes.',	listing_type='Home',	property_type='Guest suite',	room_type='Private Room',	ded_space='True',	guests='10',	beds='12',	bedsize='Queen',	common_space='Couch',	bathrooms='5',	Country='United States',	street_one='3228 higgins',	street_two='',	city='fort wayne',	state='indiana',	zip_code='46063 ',	rate='110',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum mauris non bibendum vehicula conubia nibh lacinia sollicitudin?Fringilla quis ligula ligula potenti aptent nunc habitant at.Euismod interdum dui lorem et dis elementum mi diam.Per, vel consectetur varius erat facilisi posuere feugiat.Nascetur venenatis scelerisque vehicula per rutrum mi parturient purus.Id porta vehicula a euismod vehicula sed maecenas?Neque, dolor ridiculus eros dis commodo adipiscing dictumst.Purus nam habitant quisque fringilla enim mollis posuere suscipit duis lobortis.Neque volutpat eget penatibus eros elementum aptent euismod potenti tristique!Et lorem aliquet aliquet tempor blandit mollis porttitor facilisi nibh auctor enim.',	)
    x = pick_picture()
    listing.objects.create(	title='Adipiscing, rhoncus hac lacus. Eros.',	listing_type='Home',	property_type='Condominium',	room_type='Entire Place',	ded_space='False',	guests='8',	beds='5',	bedsize='Sofa bed',	common_space='Floor Matress',	bathrooms='2',	Country='United States',	street_one='6730 55th',	street_two='',	city='santa ana',	state='california',	zip_code='92606',	rate='54',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum ultrices magnis arcu sodales curae; aptent enim duis.Feugiat pellentesque curabitur integer consequat ultricies dapibus quis?Nisl felis ut eget amet ante odio posuere sapien semper?Montes lectus mus mi consequat urna elementum leo!Fusce hac nunc egestas rutrum dapibus class consectetur arcu facilisi.Aptent convallis bibendum eget, fermentum quis mauris fames!Quam ad sagittis varius accumsan nascetur donec aenean torquent.Dictumst luctus ornare non aliquam egestas mus nullam odio ridiculus!Venenatis ornare netus justo sem vestibulum purus lobortis donec quisque.Et phasellus torquent volutpat rhoncus imperdiet porttitor montes.',	)
    x = pick_picture()
    listing.objects.create(	title='Ipsum molestie elementum mi sollicitudin.',	listing_type='Home',	property_type='In-law',	room_type='Shared Room',	ded_space='False',	guests='10',	beds='1',	bedsize='Single',	common_space='Floor Matress',	bathrooms='8',	Country='United States',	street_one='7299 eastman',	street_two='',	city='santa ana',	state='california',	zip_code='92670',	rate='282',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum est ornare non primis turpis nisl class dapibus amet dictumst suspendisse eu.Luctus tellus elementum rhoncus laoreet consectetur habitasse elit justo sapien.Lorem sociosqu massa donec, interdum eleifend urna facilisi praesent parturient in?Sagittis volutpat pulvinar porta senectus urna dis diam nisi lacus.Auctor proin vivamus quis proin eu molestie facilisis.Venenatis torquent at netus proin et quisque hendrerit cubilia mattis?In sit torquent augue quis himenaeos litora elementum, nostra dignissim pharetra aptent.Facilisis diam proin ultrices montes pretium condimentum lobortis.A varius ipsum integer mi habitasse ut montes facilisi?Ad himenaeos quis adipiscing velit senectus habitant ultricies nostra.',	)
    x = pick_picture()
    listing.objects.create(	title='Libero sociis curabitur fames posuere.',	listing_type='Home',	property_type='TownHouse',	room_type='Entire Place',	ded_space='True',	guests='7',	beds='5',	bedsize='King',	common_space='Couch',	bathrooms='1',	Country='United States',	street_one='5350 le moyne',	street_two='',	city='moreno valley',	state='california',	zip_code='92537',	rate='135',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum scelerisque malesuada suspendisse est mauris quam vulputate placerat.Nostra donec etiam feugiat vestibulum bibendum in tempus et.Ornare, accumsan sit non eros nulla aptent himenaeos dapibus consequat!At per magna imperdiet imperdiet malesuada magnis penatibus bibendum porttitor.Ante bibendum vehicula vitae quisque etiam magnis viverra sed cursus magnis.Consectetur gravida sem praesent congue nulla faucibus nec, inceptos semper lacus mauris?Natoque nascetur vel tortor torquent nascetur himenaeos, conubia augue.Pellentesque nulla interdum condimentum posuere placerat vestibulum sociis leo lacus ultrices torquent.Natoque accumsan nam bibendum dictum rhoncus tortor cubilia, phasellus etiam.Leo eu nascetur pretium ac nisi mi lacus pharetra.',	)
    x = pick_picture()
    listing.objects.create(	title='Diam cubilia ultrices diam, torquent?',	listing_type='Hotel',	property_type='In-law',	room_type='Entire Place',	ded_space='False',	guests='10',	beds='7',	bedsize='King',	common_space='Sofa Bed',	bathrooms='10',	Country='United States',	street_one='3438 flournoy',	street_two='',	city='corpus christi',	state='texas',	zip_code='78121',	rate='123',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum id egestas cras sagittis torquent libero ad volutpat erat pellentesque elit platea.Fringilla montes sed accumsan, dolor rutrum sagittis blandit venenatis.Metus mollis facilisis fusce placerat sem volutpat aptent vitae sit.Porttitor mollis turpis habitasse nulla ligula nascetur hendrerit!Massa tortor ultricies massa porta dis orci lectus quisque nostra.Justo ornare nascetur consectetur turpis hendrerit est augue senectus dictumst!Molestie non eleifend augue posuere condimentum convallis pellentesque.Eleifend mollis arcu phasellus lorem aenean adipiscing mauris mauris scelerisque lacinia dapibus.Tellus fringilla placerat tortor mattis neque facilisi habitant ipsum a quam nec.Aliquet metus neque tempor neque hendrerit himenaeos nulla dis accumsan.',	)
    x = pick_picture()
    listing.objects.create(	title='Massa elit donec ultricies metus.',	listing_type='Home',	property_type='Apartment',	room_type='Shared Room',	ded_space='True',	guests='9',	beds='13',	bedsize='Sofa bed',	common_space='Floor Matress',	bathrooms='10',	Country='United States',	street_one='2430 54th',	street_two='',	city='peoria',	state='arizona',	zip_code='85385',	rate='142',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum id mattis himenaeos quam eros ante ut ad?Convallis conubia lectus vivamus himenaeos pretium interdum nibh nibh.Maecenas luctus libero aptent vel commodo tincidunt ut posuere maecenas.Sodales pellentesque dictumst velit netus quisque himenaeos nam leo.Quam inceptos proin arcu auctor maecenas phasellus nulla sapien porta integer.Ipsum nec imperdiet parturient cursus consequat dui fusce sodales commodo mattis per?Montes eget ullamcorper gravida nullam sit cras rhoncus conubia taciti.Ad rutrum aenean dolor ridiculus viverra pulvinar a ullamcorper venenatis.Aptent mollis vivamus nullam erat pellentesque phasellus sagittis quisque etiam.Congue consequat nulla at faucibus mi risus est mattis litora varius.',	)
    x = pick_picture()
    listing.objects.create(	title='Fermentum tincidunt fermentum odio. Commodo.',	listing_type='Home',	property_type='Guest suite',	room_type='Shared Room',	ded_space='True',	guests='2',	beds='7',	bedsize='King',	common_space='Couch',	bathrooms='13',	Country='United States',	street_one='8152 norfolk rr access',	street_two='',	city='chula vista',	state='california',	zip_code='91926',	rate='180',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum lacus hendrerit porta eros ad elementum iaculis auctor feugiat magna, vitae augue.Vulputate proin nibh consequat a suspendisse, convallis justo.Erat imperdiet tellus pretium nostra; magnis tristique consequat cras aliquam sociosqu eget?Enim faucibus libero nisi sodales litora massa imperdiet iaculis ante?Mollis curae; nec ullamcorper torquent amet ad nascetur congue nullam porttitor.Ad rutrum sociis penatibus sagittis; lorem adipiscing laoreet.Leo sed proin turpis sapien felis in, justo lectus elit!Fermentum taciti leo neque, sapien phasellus tincidunt vestibulum.Integer dictumst primis sem lectus odio aliquet augue torquent elit luctus vitae.Facilisi elementum ligula imperdiet eleifend aliquam nibh id vehicula potenti diam?',	)
    x = pick_picture()
    listing.objects.create(	title='Aliquam fusce molestie litora hac.',	listing_type='Something else',	property_type='In-law',	room_type='Private Room',	ded_space='True',	guests='5',	beds='11',	bedsize='Single',	common_space='Couch',	bathrooms='7',	Country='United States',	street_one='2413 birchwood',	street_two='',	city='provo',	state='utah',	zip_code='84036',	rate='205',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum porta nisi quam viverra suspendisse mi donec mi nunc fringilla.Quis nulla cubilia vehicula lobortis magnis bibendum netus netus sapien ridiculus.Placerat suscipit consectetur nisi lobortis congue platea urna.Purus dapibus velit molestie amet cursus purus netus pellentesque maecenas.Eleifend imperdiet ipsum cubilia risus, neque hac molestie.Torquent egestas duis nec at quisque lacinia mattis.Duis vulputate suscipit torquent nibh diam urna eget pretium augue ultricies.Quisque quisque luctus bibendum rutrum aliquam sodales integer dapibus vivamus pretium nisi.Donec libero justo id sodales laoreet faucibus ante quisque arcu aliquam fusce.Varius tristique dolor convallis ante eleifend risus netus.',	)
    x = pick_picture()
    listing.objects.create(	title='Hac ornare arcu hendrerit ridiculus.',	listing_type='Home',	property_type='Apartment',	room_type='Entire Place',	ded_space='False',	guests='2',	beds='15',	bedsize='Single',	common_space='Couch',	bathrooms='4',	Country='United States',	street_one='8736 harrison',	street_two='',	city='akron',	state='ohio',	zip_code='44379',	rate='176',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum elementum cras himenaeos commodo eleifend sed conubia odio.Potenti himenaeos auctor enim semper leo justo praesent.Pharetra consectetur id, pretium taciti blandit rutrum nisl massa nibh nam.Ultrices vitae et tellus congue convallis dapibus platea montes.Quam habitant aenean himenaeos lorem pulvinar posuere scelerisque neque.Sollicitudin penatibus neque auctor lacus nisi etiam diam.Cursus nullam lacus ligula diam nam aliquam parturient.Taciti curae; auctor felis massa phasellus habitant aenean, non senectus.Nisi inceptos aptent leo ultricies fermentum libero nisi justo molestie duis.Habitant dignissim cursus aliquet dictum risus venenatis, etiam nam tellus nulla.',	)
    x = pick_picture()
    listing.objects.create(	title='Et id natoque mollis consequat.',	listing_type='Something else',	property_type='House',	room_type='Private Room',	ded_space='True',	guests='7',	beds='5',	bedsize='Sofa bed',	common_space='Floor Matress',	bathrooms='10',	Country='United States',	street_one='6528 pacific',	street_two='',	city='garland',	state='texas',	zip_code='75543',	rate='254',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum commodo nibh adipiscing montes himenaeos metus, id ornare habitant natoque.Imperdiet nibh natoque dapibus eros penatibus taciti ridiculus aenean himenaeos duis.In arcu senectus amet sit facilisis gravida nam dignissim neque.Metus vestibulum sociis urna cum suspendisse ridiculus, curae; dui senectus.Est lacinia netus maecenas ornare euismod nibh iaculis?Curae; fermentum quisque erat orci class integer per.Libero risus laoreet libero ornare non congue mauris velit?Primis dictum adipiscing sit sollicitudin suspendisse ultricies dictumst eu venenatis.Nunc porttitor facilisis sagittis augue malesuada penatibus diam ultrices.Pulvinar leo venenatis sed congue hendrerit velit tempor elit volutpat sociis.',	)
    x = pick_picture()
    listing.objects.create(	title='Sagittis purus nascetur ultrices aenean.',	listing_type='Hotel',	property_type='Condominium',	room_type='Entire Place',	ded_space='True',	guests='3',	beds='4',	bedsize='Double',	common_space='Couch',	bathrooms='1',	Country='United States',	street_one='6883 reilly',	street_two='',	city='lubbock',	state='texas',	zip_code='79906',	rate='203',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum interdum nec neque elit posuere fermentum potenti molestie pretium morbi netus.Ad lorem nascetur in primis aliquam fringilla platea maecenas.Gravida venenatis suspendisse sed cursus sollicitudin id egestas purus fames.Mattis aptent auctor tortor senectus sem dis rutrum nostra aenean erat.Elit primis, sapien netus euismod consectetur iaculis placerat!Dui torquent eleifend curabitur vehicula placerat eros, accumsan condimentum proin.Mus sit nascetur potenti ultricies convallis purus tristique.Senectus, fames urna senectus nec nullam magnis conubia luctus quam magna.Vehicula rutrum faucibus nunc quis vel odio vestibulum nec eleifend parturient.Vitae mollis habitasse turpis sapien adipiscing lobortis, rutrum porta potenti quam.',	)
    x = pick_picture()
    listing.objects.create(	title='Sodales id porttitor habitant vulputate.',	listing_type='Home',	property_type='TownHouse',	room_type='Private Room',	ded_space='True',	guests='2',	beds='9',	bedsize='King',	common_space='Sofa Bed',	bathrooms='2',	Country='United States',	street_one='1547 natchez',	street_two='',	city='santa ana',	state='california',	zip_code='92662',	rate='124',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum ipsum accumsan inceptos vehicula viverra litora arcu auctor felis suscipit.Id neque elementum vitae rhoncus augue dui sit dolor.Interdum metus taciti cum viverra rhoncus et erat metus.Cubilia parturient ridiculus platea volutpat ultrices urna vel placerat blandit dictumst volutpat.Turpis mollis id sed condimentum pretium montes fringilla.Congue, velit facilisis est augue vehicula cursus consequat accumsan.Curabitur felis ultrices dapibus tellus etiam mattis lacus!Magnis dictum phasellus dolor tellus proin adipiscing mauris tortor aliquet torquent.Molestie eget nisi congue bibendum elementum venenatis morbi phasellus.Purus sagittis justo justo ligula cursus fames eu justo dictumst mauris.',	)
    x = pick_picture()
    listing.objects.create(	title='Ac vestibulum velit curabitur parturient.',	listing_type='Something else',	property_type='TownHouse',	room_type='Entire Place',	ded_space='True',	guests='9',	beds='8',	bedsize='Sofa bed',	common_space='Floor Matress',	bathrooms='11',	Country='United States',	street_one='7320 rosemont',	street_two='',	city='cleveland',	state='ohio',	zip_code='44655',	rate='114',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum accumsan suscipit, justo duis orci tempor purus in.Risus magnis dignissim nunc, tempus amet habitant fringilla id proin.Dictumst senectus pellentesque primis pretium mauris faucibus praesent urna conubia ligula.Nostra sodales conubia tellus est sollicitudin class felis tincidunt lacus.Mattis suscipit tristique ac urna ullamcorper litora hac tempus scelerisque vulputate hendrerit.Id blandit orci congue tempor varius placerat litora erat senectus himenaeos.Aliquam justo pulvinar himenaeos netus rutrum pretium cursus habitant blandit arcu.Nostra proin quis, ad cras arcu lobortis arcu.Turpis fermentum ad auctor amet, tellus senectus elit habitant class.Senectus, tristique aptent pulvinar cum nam consectetur diam augue potenti montes.',	)
    x = pick_picture()
    listing.objects.create(	title='Tempor placerat erat sagittis. Duis.',	listing_type='Something else',	property_type='Apartment',	room_type='Private Room',	ded_space='True',	guests='11',	beds='7',	bedsize='Double',	common_space='Floor Matress',	bathrooms='15',	Country='United States',	street_one='5453 78th',	street_two='',	city='salem',	state='oregon',	zip_code='97331',	rate='249',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum praesent amet pellentesque porta est justo, potenti est.Elementum nisl sodales morbi etiam quisque sollicitudin in.Arcu amet cubilia, praesent rhoncus malesuada dapibus mauris.Praesent montes pretium volutpat suscipit, placerat a malesuada iaculis neque.Porttitor mauris integer vulputate ornare accumsan cras placerat.Sociis pharetra nisl rhoncus bibendum taciti platea tempor.Lectus primis scelerisque aenean curabitur diam, fringilla cum vivamus.Etiam sit mi gravida nostra facilisi per amet mollis eleifend elit malesuada.Purus lorem montes placerat potenti felis scelerisque auctor tempor.Elit pretium dictum est magnis feugiat magna habitasse venenatis.',	)
    x = pick_picture()
    listing.objects.create(	title='Tortor non curabitur vitae, velit.',	listing_type='Hotel',	property_type='TownHouse',	room_type='Entire Place',	ded_space='True',	guests='3',	beds='2',	bedsize='King',	common_space='Sofa Bed',	bathrooms='10',	Country='United States',	street_one='5231 96th',	street_two='',	city='manchester',	state='new hampshire',	zip_code='3105',	rate='68',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum porta aliquam nam pellentesque cum at convallis et.Tellus orci at rutrum condimentum cum dis placerat lorem eget.Maecenas condimentum eros interdum nunc morbi velit commodo.Per varius laoreet dui felis adipiscing quisque semper.Ridiculus, netus per nisi dui dictum sociosqu habitasse sem.Eros pulvinar torquent elementum quis varius purus magna conubia leo.Id mauris sapien curabitur hendrerit inceptos convallis sociosqu.Luctus nullam nisl sodales luctus sem rutrum montes taciti.Platea inceptos amet lectus mattis dui; magnis integer interdum nascetur libero.Accumsan potenti himenaeos diam mus cursus ante phasellus volutpat dignissim.',	)
    x = pick_picture()
    listing.objects.create(	title='Mi fermentum amet dictumst tristique.',	listing_type='Something else',	property_type='TownHouse',	room_type='Shared Room',	ded_space='True',	guests='7',	beds='5',	bedsize='King',	common_space='Sofa Bed',	bathrooms='10',	Country='United States',	street_one='3812 julian',	street_two='',	city='dayton',	state='ohio',	zip_code='45399',	rate='168',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum vulputate sollicitudin non adipiscing ornare porttitor senectus facilisis.Parturient potenti montes quis proin dapibus aenean cursus?Penatibus venenatis curabitur faucibus et hac sodales dapibus maecenas fringilla.Dictumst congue ipsum tortor euismod taciti, potenti consequat vehicula ornare vehicula.Erat rhoncus himenaeos sodales at ipsum litora sollicitudin.Eget habitant inceptos id elementum commodo scelerisque cum pulvinar gravida sit.Luctus leo, viverra morbi cubilia tincidunt ullamcorper consectetur nibh dui sem.Volutpat fames facilisis tellus donec, convallis volutpat netus porta.Lobortis dolor libero montes erat habitasse diam lacus suscipit lobortis pretium dapibus.Litora, nisl pharetra iaculis risus mi sodales torquent.',	)
    x = pick_picture()
    listing.objects.create(	title='Phasellus cubilia potenti non egestas!',	listing_type='Home',	property_type='Condominium',	room_type='Private Room',	ded_space='False',	guests='7',	beds='5',	bedsize='Double',	common_space='Sofa Bed',	bathrooms='11',	Country='United States',	street_one='5480 gale',	street_two='',	city='buffalo',	state='new york',	zip_code='14246',	rate='159',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum facilisis tincidunt mi mollis cubilia dolor sem fermentum!Montes sociosqu et condimentum elementum porta justo posuere molestie at diam senectus?Vestibulum placerat vestibulum fusce vel laoreet sapien dui et integer fringilla!Dis elit imperdiet odio habitasse in orci diam cum taciti.Bibendum convallis vulputate suspendisse lectus suscipit nunc ipsum dapibus interdum donec natoque.Sodales pharetra vehicula sociosqu lectus suscipit facilisis, mollis mi nisi sagittis.Lectus porttitor justo cras class quisque lacus pharetra sociosqu.Orci fusce ornare sapien mus elit tellus lorem consectetur.Neque, bibendum ac convallis volutpat vulputate rhoncus aliquam risus praesent justo.Sagittis sociosqu elementum justo netus taciti tempor maecenas litora.',	)
    x = pick_picture()
    listing.objects.create(	title='Litora curabitur dui sociosqu quis.',	listing_type='Something else',	property_type='TownHouse',	room_type='Shared Room',	ded_space='True',	guests='6',	beds='2',	bedsize='King',	common_space='Floor Matress',	bathrooms='11',	Country='United States',	street_one='3596 wayne',	street_two='',	city='surprise',	state='arizona',	zip_code='85383',	rate='231',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum suscipit class amet consectetur rutrum augue pretium vitae.Maecenas ultricies torquent senectus id odio litora quis nec risus.Non aliquet; nam nibh pretium quisque ipsum erat enim.Tempus primis aptent malesuada dolor auctor potenti pellentesque torquent iaculis nec.Blandit malesuada habitant congue cubilia parturient, accumsan posuere.Etiam venenatis blandit congue phasellus neque aliquam lacus aliquam semper himenaeos.Tristique aenean primis sem elit hac porta non senectus.Leo lobortis hac mi, praesent ipsum facilisi pretium.Pellentesque posuere et magnis sit curae; vulputate non neque.Curabitur facilisi, nam massa laoreet magnis lorem ipsum ultricies pulvinar nam pretium?',	)
    x = pick_picture()
    listing.objects.create(	title='Rutrum habitasse faucibus at etiam.',	listing_type='Home',	property_type='Guesthouse',	room_type='Entire Place',	ded_space='True',	guests='1',	beds='14',	bedsize='Sofa bed',	common_space='Sofa Bed',	bathrooms='0',	Country='United States',	street_one='2318 cityfront plaza',	street_two='',	city='boise city',	state='idaho',	zip_code='83119',	rate='163',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum felis pharetra convallis cras nam ornare feugiat nisl mi dapibus risus?Semper, mattis et fusce lacus porttitor varius curabitur sapien varius et sociis.Velit sociis posuere pulvinar rutrum dictumst commodo odio mauris tellus sollicitudin etiam!Velit sem taciti fusce nullam nunc inceptos bibendum curae; sit fames rhoncus.Urna ullamcorper molestie tellus aliquam, phasellus fringilla ultricies quam mi.Sollicitudin dictum dictum id mauris facilisis sagittis sociosqu parturient lorem.Ante eleifend lacus himenaeos in tincidunt porta, eu ac.Metus vulputate ultricies felis dictum, netus tincidunt donec sem.Ridiculus magna, netus tristique neque ac gravida leo conubia vivamus commodo.Sit massa natoque vel dui nibh ligula varius nostra et magna ad.',	)
    x = pick_picture()
    listing.objects.create(	title='Mus cum sociis habitant dapibus.',	listing_type='Hotel',	property_type='Condominium',	room_type='Shared Room',	ded_space='False',	guests='2',	beds='12',	bedsize='Queen',	common_space='Couch',	bathrooms='2',	Country='United States',	street_one='2799 lunt',	street_two='',	city='huntsville',	state='alabama',	zip_code='35807',	rate='163',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum malesuada nisi rutrum nisi eros aptent vulputate accumsan.Neque est fusce a felis dignissim taciti lectus erat risus.Cubilia cras sociis at consequat integer orci in mi suspendisse.Sociis nam eu massa tincidunt hac tristique sem.Pulvinar orci, lacus phasellus sagittis eros nam libero ad ad congue ligula.Magna torquent condimentum ullamcorper erat nulla parturient aliquet nascetur phasellus malesuada.Posuere fusce sodales laoreet ut dolor vitae ligula?Aptent volutpat ligula consectetur nunc iaculis luctus ultrices aptent et sociis mus.Sem feugiat cubilia diam augue platea cubilia adipiscing consequat?Semper proin feugiat bibendum sapien senectus amet nulla praesent.',	)
    x = pick_picture()
    listing.objects.create(	title='Dictumst viverra, platea rhoncus natoque.',	listing_type='Home',	property_type='Apartment',	room_type='Private Room',	ded_space='False',	guests='5',	beds='2',	bedsize='Double',	common_space='Couch',	bathrooms='5',	Country='United States',	street_one='4036 81st',	street_two='',	city='birmingham',	state='alabama',	zip_code='35027',	rate='228',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum commodo fringilla imperdiet lobortis ridiculus vivamus accumsan vivamus rutrum class ipsum?Condimentum pellentesque sociosqu risus porta erat dis lacinia, lacus habitant dignissim hendrerit.Imperdiet et sem orci ipsum, amet conubia nam lorem fusce primis.Inceptos sodales vel curae; vestibulum habitasse tempus ipsum adipiscing commodo mattis commodo.Cubilia nullam sapien hac nullam lectus egestas ut elementum posuere sociis.Fermentum dictum sollicitudin id bibendum donec etiam facilisi dui.Consequat gravida rutrum et sollicitudin pellentesque fringilla integer!Tristique pellentesque curae; non litora tristique mattis sem magna pulvinar libero.Neque viverra imperdiet sodales habitant libero elit penatibus, consectetur egestas.Habitant mattis viverra sagittis nam donec viverra volutpat habitant fringilla cubilia tempor.',	)
    x = pick_picture()
    listing.objects.create(	title='Mattis netus parturient tincidunt. Pretium.',	listing_type='Hotel',	property_type='Guest suite',	room_type='Entire Place',	ded_space='True',	guests='15',	beds='4',	bedsize='King',	common_space='Couch',	bathrooms='10',	Country='United States',	street_one='6570 ludlam',	street_two='',	city='chesapeake',	state='virginia',	zip_code='23396',	rate='61',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum convallis penatibus sapien sociis duis eros parturient phasellus aliquet senectus.Platea mollis per imperdiet, ad torquent egestas tincidunt fermentum integer tempor tincidunt?Duis potenti, orci vivamus torquent vulputate velit inceptos?Malesuada facilisi conubia sociosqu fusce euismod habitant varius tellus mi malesuada.Neque porttitor suscipit metus vitae montes pellentesque aliquam.Enim placerat mattis euismod velit feugiat feugiat erat mi sodales nec.Aliquet dolor senectus lobortis ut sociis, habitasse aenean nunc leo nam.Mollis cubilia magna aptent consequat cum commodo ullamcorper donec euismod maecenas vestibulum.Pulvinar curabitur platea quam proin libero purus mattis eget.Rhoncus ultrices penatibus tellus ipsum class parturient venenatis diam ac.',	)
    x = pick_picture()
    listing.objects.create(	title='Facilisis semper cursus nulla, eget.',	listing_type='Something else',	property_type='Guesthouse',	room_type='Entire Place',	ded_space='False',	guests='12',	beds='13',	bedsize='Double',	common_space='Floor Matress',	bathrooms='8',	Country='United States',	street_one='476 mandell',	street_two='',	city='birmingham',	state='alabama',	zip_code='35013',	rate='229',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum libero, lacus adipiscing eros bibendum etiam pretium habitant quisque mattis!Magna potenti ultrices proin nulla ipsum habitasse cubilia fringilla platea per in.Fermentum feugiat, parturient gravida in dis conubia curae; tellus.Dolor elit interdum suscipit diam metus ultricies ullamcorper non.Euismod aliquet etiam semper magnis ut tempus velit.Venenatis id cum ac nullam ridiculus faucibus viverra varius morbi morbi malesuada.Neque euismod amet turpis cursus facilisis nisl natoque fermentum ad eros netus.Ligula posuere eget suspendisse sed parturient velit mollis accumsan, magnis suspendisse.Consequat ultrices dignissim elementum dapibus, sed varius senectus sollicitudin purus pulvinar venenatis.Proin dictumst sollicitudin porttitor, sociis nunc dictum primis.',	)
    x = pick_picture()
    listing.objects.create(	title='Class accumsan erat non. Magnis.',	listing_type='Something else',	property_type='TownHouse',	room_type='Private Room',	ded_space='True',	guests='13',	beds='6',	bedsize='King',	common_space='Sofa Bed',	bathrooms='8',	Country='United States',	street_one='479 midway airport lower',	street_two='',	city='overland park',	state='kansas',	zip_code='66201',	rate='297',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum maecenas vulputate maecenas himenaeos cursus a luctus, porta curabitur donec.Porttitor egestas sodales risus dolor viverra condimentum ultrices hac dolor.Netus et nec urna quisque orci ut nulla sociis.Natoque rhoncus egestas torquent mollis vitae est aliquam enim adipiscing non quam.Himenaeos augue, condimentum natoque consequat ipsum pulvinar morbi consequat rhoncus et venenatis?Aenean facilisi rutrum consectetur neque ultricies morbi quis!A cras ac maecenas per feugiat dis eleifend dictumst auctor.Sagittis condimentum felis erat dolor per turpis donec varius curae; pretium posuere.Suscipit dignissim nisl nullam leo ornare, sapien neque vulputate varius!Lacus phasellus venenatis posuere pulvinar ad praesent phasellus scelerisque duis volutpat.',	)
    x = pick_picture()
    listing.objects.create(	title='Ultricies dolor metus ipsum. Aenean.',	listing_type='Home',	property_type='In-law',	room_type='Entire Place',	ded_space='False',	guests='2',	beds='3',	bedsize='Sofa bed',	common_space='Floor Matress',	bathrooms='7',	Country='United States',	street_one='4158 ford city dr',	street_two='',	city='baltimore',	state='maryland',	zip_code='21674',	rate='90',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum tempus ligula dictum himenaeos risus eleifend gravida fermentum habitasse convallis auctor porta?Ridiculus primis nunc cras ad ante senectus in sem.Dictumst a rutrum orci mi himenaeos ac pulvinar inceptos sollicitudin fermentum dictum.Natoque dapibus nibh luctus semper faucibus ligula quam phasellus eros.Platea praesent iaculis odio hendrerit nisl lectus interdum facilisis mus?Congue penatibus, etiam dictum accumsan eget fames maecenas arcu.Malesuada netus etiam class felis mattis cum nostra lacus purus tempus.Justo dolor felis rutrum facilisi, euismod suspendisse cursus auctor.Posuere senectus pharetra congue bibendum aliquam aptent curabitur.Fames placerat quam integer faucibus gravida litora praesent?',	)
    x = pick_picture()
    listing.objects.create(	title='Ornare et senectus cursus nam.',	listing_type='Hotel',	property_type='TownHouse',	room_type='Shared Room',	ded_space='True',	guests='6',	beds='6',	bedsize='Queen',	common_space='Couch',	bathrooms='15',	Country='United States',	street_one='8757 washington park',	street_two='',	city='worcester',	state='massachusetts',	zip_code='1666',	rate='194',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum nam facilisis sem facilisi dictumst, accumsan malesuada sed per tempor placerat volutpat.Augue bibendum quis vulputate maecenas suscipit non habitasse.Nullam porta mauris mauris suspendisse duis tincidunt laoreet turpis.Tristique congue himenaeos feugiat conubia est etiam, at dis vehicula tempor.Tristique fringilla congue diam magnis nostra odio dictumst, viverra fusce adipiscing.Netus duis tincidunt, lacus litora at ultrices elementum scelerisque justo.Ut scelerisque lobortis platea tempus cursus et facilisi arcu aliquet feugiat convallis?Odio, nam sit conubia phasellus posuere litora interdum imperdiet torquent ut.Nisi placerat mollis taciti mauris vehicula condimentum elementum blandit habitasse?Fames conubia nascetur felis erat eu a taciti sociis proin.',	)
    x = pick_picture()
    listing.objects.create(	title='Malesuada conubia at commodo ad.',	listing_type='Something else',	property_type='Guesthouse',	room_type='Shared Room',	ded_space='False',	guests='7',	beds='15',	bedsize='Sofa bed',	common_space='Floor Matress',	bathrooms='2',	Country='United States',	street_one='5805 dan ryan marquette rd',	street_two='',	city='sacramento',	state='california',	zip_code='95592',	rate='64',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum tortor condimentum conubia cras ante consectetur eleifend sapien, neque mauris.Nisi elit fames eros rutrum condimentum nullam lectus etiam facilisis aliquet elit.Eleifend convallis posuere quis curabitur dolor interdum dolor accumsan elit.Mauris sed suscipit dis feugiat eleifend platea venenatis quam.Consectetur dictum integer viverra, blandit luctus fusce augue!Neque fringilla taciti bibendum sem commodo sollicitudin dui metus tempor tellus tellus.Dis nullam rutrum tincidunt sociis varius scelerisque sed nullam!Nam malesuada cum phasellus blandit rhoncus, laoreet penatibus.Mattis condimentum convallis integer aptent nullam, inceptos tristique.Urna habitant justo lacus etiam ad conubia mattis urna.',	)
    x = pick_picture()
    listing.objects.create(	title='Sit dictum mauris eleifend accumsan.',	listing_type='Something else',	property_type='In-law',	room_type='Private Room',	ded_space='False',	guests='16',	beds='4',	bedsize='Double',	common_space='Sofa Bed',	bathrooms='11',	Country='United States',	street_one='2887 wilmot',	street_two='',	city='stockton',	state='california',	zip_code='95166 ',	rate='52',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum morbi mus nisi accumsan ultricies et aliquet at ut gravida dolor.Euismod in aliquet vel massa vestibulum taciti magna libero suscipit.Sodales montes aliquam elementum nullam erat neque nullam, hendrerit aenean?Himenaeos lacinia eget pellentesque ultricies imperdiet facilisi laoreet.Mus eu primis felis adipiscing praesent sodales ante condimentum laoreet fringilla.Netus cubilia semper ligula semper neque ullamcorper vestibulum turpis maecenas lobortis.Mattis suspendisse curabitur a morbi consequat tempus sociis himenaeos vehicula.Tempor consectetur mollis natoque mollis rutrum malesuada etiam scelerisque elit massa luctus.Praesent ultrices litora ullamcorper, mi justo rutrum porta curae; fermentum.Neque erat justo augue penatibus bibendum; lobortis donec.',	)
    x = pick_picture()
    listing.objects.create(	title='Parturient litora velit ultricies nascetur?',	listing_type='Hotel',	property_type='House',	room_type='Private Room',	ded_space='False',	guests='9',	beds='12',	bedsize='Single',	common_space='Couch',	bathrooms='4',	Country='United States',	street_one='1016 st joseph',	street_two='',	city='greensboro',	state='north carolina',	zip_code='27494',	rate='115',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum et tellus quis montes turpis nunc, maecenas aptent nunc dui turpis.Hac sem eleifend at velit velit phasellus congue venenatis nulla?Ante laoreet nunc habitasse elit nullam facilisi viverra nec suscipit pulvinar quam.Accumsan vestibulum ornare facilisi dis vivamus, in tortor sagittis blandit et penatibus.Elementum malesuada curae; montes duis elementum purus leo non posuere.Curabitur facilisi consequat cum ante eu dolor facilisis sollicitudin vivamus ridiculus dapibus.Tempor malesuada conubia dignissim fringilla risus sollicitudin porttitor etiam at!Habitasse molestie mattis elit ligula nulla torquent montes commodo facilisis porta inceptos!Posuere fringilla rutrum erat ut libero porttitor netus ridiculus.Laoreet mattis lobortis sed arcu porta praesent lobortis.',	)
    x = pick_picture()
    listing.objects.create(	title='Fames a conubia taciti maecenas.',	listing_type='Something else',	property_type='Condominium',	room_type='Private Room',	ded_space='False',	guests='3',	beds='14',	bedsize='Sofa bed',	common_space='Couch',	bathrooms='14',	Country='United States',	street_one='8533 dunbar',	street_two='',	city='montpelier',	state='vermont',	zip_code='5649',	rate='88',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum sem porta risus eu class nostra mi velit felis posuere velit.Sed sociis ac nulla a erat lobortis litora.Ultricies tempor condimentum elementum viverra hac a accumsan neque ultrices.Cras faucibus dapibus natoque libero commodo lorem turpis et.Dictum feugiat vitae maecenas tincidunt facilisis in ut et.Sociis ultrices nibh per litora velit libero convallis malesuada curae; volutpat!Nullam tempor ornare porta himenaeos rutrum dui id litora.Ridiculus vulputate laoreet leo quam congue iaculis dictumst fames duis.Curabitur rutrum, cras pharetra eleifend adipiscing nam eros.Pharetra nulla donec venenatis litora molestie molestie habitant pellentesque mattis arcu.',	)
    x = pick_picture()
    listing.objects.create(	title='Iaculis neque mollis facilisi porttitor.',	listing_type='Something else',	property_type='Guesthouse',	room_type='Private Room',	ded_space='False',	guests='11',	beds='8',	bedsize='Single',	common_space='Couch',	bathrooms='9',	Country='United States',	street_one='4169 marshfield',	street_two='',	city='columbia',	state='south carolina',	zip_code='29014',	rate='255',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum fermentum imperdiet vivamus cubilia lobortis proin velit nostra senectus magna.Nam orci sociis, dapibus condimentum erat ipsum sollicitudin convallis elementum.Adipiscing non pharetra nascetur montes viverra eu non feugiat!A feugiat nostra ultrices elementum hac venenatis tempor tincidunt risus.Luctus condimentum, quisque ornare ridiculus fames porttitor tempor vulputate sollicitudin vivamus.Sagittis praesent elit feugiat consequat suspendisse odio integer nullam.Nascetur platea habitant parturient dignissim bibendum etiam purus risus aenean.Habitant auctor ad venenatis phasellus fusce condimentum augue, per aliquet taciti justo.Blandit orci maecenas fringilla dictum dignissim mollis ornare.Tortor leo dui elit fringilla morbi nascetur nisl.',	)
    x = pick_picture()
    listing.objects.create(	title='Sociosqu porttitor torquent vehicula integer!',	listing_type='Something else',	property_type='House',	room_type='Entire Place',	ded_space='True',	guests='8',	beds='14',	bedsize='Sofa bed',	common_space='Floor Matress',	bathrooms='7',	Country='United States',	street_one='9002 hamlet',	street_two='',	city='moreno valley',	state='california',	zip_code='92538',	rate='286',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum erat torquent condimentum consequat posuere purus integer habitant in.Id blandit dignissim sem metus velit phasellus porta felis proin!Eros consequat egestas eleifend sodales gravida rutrum torquent morbi fusce vulputate?Morbi imperdiet adipiscing rhoncus, euismod nostra curae; proin nullam vulputate suscipit litora?Vehicula at est dictum pulvinar blandit aenean dis lacinia.Nostra himenaeos potenti cras amet feugiat taciti turpis augue!Morbi, felis placerat posuere magnis in habitasse nullam dis elit dis.Semper cum ligula tellus cum curae; ligula luctus?Etiam dictum mi a massa nullam lorem ipsum?Ante est class arcu, hendrerit faucibus euismod ante rutrum.',	)
    x = pick_picture()
    listing.objects.create(	title='Facilisis lobortis sem sed ullamcorper.',	listing_type='Something else',	property_type='Guesthouse',	room_type='Entire Place',	ded_space='False',	guests='8',	beds='15',	bedsize='Single',	common_space='Sofa Bed',	bathrooms='11',	Country='United States',	street_one='5733 richmond',	street_two='',	city='madison',	state='wisconsin',	zip_code='53928',	rate='143',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum per cras ultricies ornare tortor cras posuere senectus maecenas tempus.Duis vitae porttitor lacinia imperdiet montes nisl sociosqu!Malesuada, habitant tortor hac potenti lacinia enim penatibus natoque elit odio.Nostra litora ultrices adipiscing praesent vivamus egestas dignissim nunc.Sodales ultricies mus varius est habitasse ligula magnis cubilia ultrices adipiscing dolor.Dictumst dignissim semper nullam praesent massa lacinia lacinia magna sed!Luctus dictum, a ante habitasse mus vel tempor.Quis placerat dui tellus erat vehicula integer mauris ante, pharetra cursus!Ornare nibh risus mus magna bibendum maecenas, dapibus eget.Fermentum morbi ridiculus class euismod porttitor fames himenaeos.',	)
    x = pick_picture()
    listing.objects.create(	title='Ullamcorper duis pellentesque blandit! Dignissim.',	listing_type='Hotel',	property_type='In-law',	room_type='Shared Room',	ded_space='False',	guests='12',	beds='11',	bedsize='Single',	common_space='Couch',	bathrooms='3',	Country='United States',	street_one='1462 sawyer',	street_two='',	city='jersey city',	state='new jersey',	zip_code='7954',	rate='243',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum metus ornare ridiculus primis integer vitae, primis etiam himenaeos ornare posuere facilisis.Sem aliquet fermentum praesent cubilia amet cursus cursus lorem senectus!Nisi viverra convallis leo suspendisse nascetur himenaeos luctus massa sociis.Vivamus gravida euismod at mauris ante rutrum blandit id.Enim felis molestie lobortis nam quis, ut augue rutrum nec.Posuere imperdiet sed vivamus mauris inceptos sociis interdum donec sociis metus ipsum.Elit lectus diam sociosqu feugiat himenaeos dui varius donec consectetur massa platea.Sociosqu consequat cursus lacinia blandit inceptos iaculis non sed mattis porttitor ad!Cras condimentum conubia dui nostra proin vivamus primis ornare.Aenean nascetur risus aliquet torquent convallis enim risus.',	)
    x = pick_picture()
    listing.objects.create(	title='Aliquam sagittis euismod arcu sagittis?',	listing_type='Something else',	property_type='Guest suite',	room_type='Private Room',	ded_space='False',	guests='6',	beds='12',	bedsize='Double',	common_space='Floor Matress',	bathrooms='11',	Country='United States',	street_one='1207 major',	street_two='',	city='irving',	state='texas',	zip_code='75092',	rate='275',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum ad senectus vitae accumsan praesent et rutrum himenaeos feugiat ultrices.Vivamus suscipit dapibus nostra penatibus nibh sem platea feugiat urna felis?Aenean at luctus urna egestas dis adipiscing sociosqu cum magnis.Proin diam eget accumsan arcu augue fames mollis sociis montes!Class congue augue vehicula vehicula malesuada ultrices nulla himenaeos id orci ligula.Elit pellentesque pulvinar penatibus egestas sollicitudin litora platea posuere taciti erat.Sodales etiam pharetra id netus ante ullamcorper laoreet nisi penatibus euismod auctor?Sit magna mi eleifend litora ut, etiam id id penatibus.Quam condimentum congue pellentesque curae; cras tristique tempor adipiscing porttitor ac dictum.Sit phasellus consequat tortor neque vitae primis vulputate.',	)
    x = pick_picture()
    listing.objects.create(	title='Et dictum lacinia faucibus sollicitudin?',	listing_type='Something else',	property_type='House',	room_type='Shared Room',	ded_space='False',	guests='13',	beds='12',	bedsize='Single',	common_space='Couch',	bathrooms='3',	Country='United States',	street_one='7416 fuller',	street_two='',	city='boise city',	state='idaho',	zip_code='83799',	rate='66',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum donec mollis justo nascetur habitant, per hac facilisis.Maecenas egestas tincidunt euismod sit odio nisl venenatis.Eget pretium conubia vitae nulla tristique lobortis eget nec magna ornare.Condimentum ante ut suscipit platea ut quam suscipit dis facilisis vitae aptent.Turpis mi cras non sapien proin varius consequat aliquet ridiculus?Tortor eleifend quisque curabitur sociosqu nisi vehicula sed.Feugiat ipsum mollis ad porta iaculis morbi magnis sem.Risus porta sed aptent libero ullamcorper interdum montes convallis sollicitudin elementum vestibulum.Vulputate dignissim iaculis curae; convallis habitant quis magna.Volutpat quis integer ullamcorper etiam velit et potenti bibendum turpis cras porta.',	)
    x = pick_picture()
    listing.objects.create(	title='Rhoncus nullam praesent gravida hac.',	listing_type='Home',	property_type='Apartment',	room_type='Shared Room',	ded_space='False',	guests='6',	beds='6',	bedsize='Single',	common_space='Sofa Bed',	bathrooms='1',	Country='United States',	street_one='7098 kedzie',	street_two='',	city='amarillo',	state='texas',	zip_code='79160',	rate='82',	photo1='uploads/2017/10/house'+str(x)+'.1.jpg',	photo2='uploads/2017/10/house'+str(x)+'.2.jpg',	photo3='uploads/2017/10/house'+str(x)+'.3.jpg',	photo4='uploads/2017/10/house'+str(x)+'.4.jpg',	photo5='uploads/2017/10/house'+str(x)+'.5.jpg',	photo6='uploads/2017/10/house'+str(x)+'.6.jpg',	description='Lorem ipsum blandit, sodales dictum dis nunc amet magna tortor.Interdum sagittis sociosqu lorem mauris dignissim urna ornare cras.Ultricies dictumst ornare eros proin est cursus vel placerat justo.Ullamcorper duis cras venenatis lorem, sed porttitor magna.Sociis mattis quis duis fames ut, habitasse integer euismod cursus imperdiet.A iaculis ornare fusce inceptos a taciti habitant class nibh luctus.Magnis ad tincidunt vulputate mus inceptos et metus nibh.Urna nunc interdum tincidunt imperdiet gravida convallis sapien nunc tempor class.Nibh ultrices dis luctus lorem ullamcorper ultricies ultrices.Quam adipiscing semper tortor integer sit fames rutrum elementum ut erat urna.',	)
    return


def pick_picture():
    num = randint(1,6)
    return (num)
def pick_user():
    num = randint(1,50)
    return (num)


cities = ['New York',
          'Los Angeles',
          'Chicago',
          'Houston',
          'Phoenix',
          'Philadelphia',
          'San Antonio',
          'San Diego',
          'Dallas',
          'San Jose',
          'Austin',
          'Jacksonville',
          'San Francisco',
          'Columbus',
          'Indianapolis',
          'Forth Worth',
          'Charlotte',
          'Seattle',
          'Denver',
          'El Paso',
          'Washington',
          'Boston',
          'Detroit',
          'Nashville',
          'Memphis',
          'Portland',
          'Oklahoma City',
          'Las Vegas',
          'Louisville',
          'Baltimore',
          'Milwaukee',
          'Albuquerque',
          'Tucson',
          'Fresno',
          'Sacramento',
          'Mesa',
          'Kansas City',
          'Atlanta',
          'New Orleans',
          'Minneapolis',
          'St. Louis',
          ]

titles = ['Natoque donec aliquet ut sociosqu.',
          'Amet commodo porttitor conubia odio!',
          'Urna velit sagittis congue blandit?',
          'Sodales rutrum, cursus lorem curabitur.',
          'Faucibus nostra suscipit id cursus.',
          'Nibh netus elementum pulvinar magnis.',
          'Diam ultrices integer posuere varius.',
          'Ornare accumsan augue senectus faucibus.',
          'Urna ullamcorper curae; diam quam.',
          'Aenean ipsum pharetra, interdum ipsum.',
          'Curae; cum dapibus orci, ipsum.',
          'Lorem a proin penatibus mollis.',
          'Curabitur per arcu tincidunt conubia.',
          'Sollicitudin nascetur curabitur tempor montes.',
          'Adipiscing, rhoncus hac lacus. Eros.',
          'Ipsum molestie elementum mi sollicitudin.',
          'Libero sociis curabitur fames posuere.',
          'Diam cubilia ultrices diam, torquent?',
          'Massa elit donec ultricies metus.',
          'Fermentum tincidunt fermentum odio. Commodo.',
          'Aliquam fusce molestie litora hac.',
          'Hac ornare arcu hendrerit ridiculus.',
          'Et id natoque mollis consequat.',
          'Sagittis purus nascetur ultrices aenean.',
          'Sodales id porttitor habitant vulputate.',
          'Ac vestibulum velit curabitur parturient.',
          'Tempor placerat erat sagittis. Duis.',
          'Tortor non curabitur vitae, velit.',
          'Mi fermentum amet dictumst tristique.',
          'Phasellus cubilia potenti non egestas!',
          'Litora curabitur dui sociosqu quis.',
          'Rutrum habitasse faucibus at etiam.',
          'Mus cum sociis habitant dapibus.',
          'Dictumst viverra, platea rhoncus natoque.',
          'Mattis netus parturient tincidunt. Pretium.',
          'Facilisis semper cursus nulla, eget.',
          'Class accumsan erat non. Magnis.',
          'Ultricies dolor metus ipsum. Aenean.',
          'Ornare et senectus cursus nam.',
          'Malesuada conubia at commodo ad.',
          'Sit dictum mauris eleifend accumsan.',
          'Parturient litora velit ultricies nascetur?',
          'Fames a conubia taciti maecenas.',
          'Iaculis neque mollis facilisi porttitor.',
          'Sociosqu porttitor torquent vehicula integer!',
          'Facilisis lobortis sem sed ullamcorper.',
          'Ullamcorper duis pellentesque blandit! Dignissim.',
          'Aliquam sagittis euismod arcu sagittis?',
          'Et dictum lacinia faucibus sollicitudin?',
          'Rhoncus nullam praesent gravida hac.',
          ]
